In [1]:
#Task 1: Create foodie.db with a Restaurants table
import sqlite3

connection = sqlite3.connect("foodie.db")
cursor = connection.cursor()

cursor.execute("DROP TABLE IF EXISTS Restaurants")
cursor.execute("""
    CREATE TABLE Restaurants (
        id INTEGER PRIMARY KEY,
        name TEXT,
        cuisine TEXT,
        rating REAL
    )
""")

connection.commit()
print("Database and table created")

Database and table created

In [2]:
#Task 2: Insert 3 restaurants, fetch ones with rating above 4.0, print names
cursor.execute("INSERT INTO Restaurants VALUES (1, 'Swagat', 'Gujarati', 4.3)")
cursor.execute("INSERT INTO Restaurants VALUES (2, 'Cafe Delight', 'Continental', 3.7)")
cursor.execute("INSERT INTO Restaurants VALUES (3, 'Mainland China', 'Chinese', 4.7)")

connection.commit()

cursor.execute("SELECT name FROM Restaurants WHERE rating > 4.0")
results = cursor.fetchall()

for row in results:
    print(row[0])

Swagat
Mainland China

In [3]:
#Task 3: Load Restaurants table into a pandas DataFrame, show top 2 rows
import pandas as pd

df = pd.read_sql_query("SELECT * FROM Restaurants", connection)
df.head(2)

   id          name      cuisine  rating
0   1        Swagat     Gujarati     4.3
1   2  Cafe Delight  Continental     3.7

In [4]:
#Task 4: Add delivery_charge column and calculate final_rating
df["delivery_charge"] = 50

df["final_rating"] = df.apply(
    lambda row: row["rating"] + 0.1 if row["cuisine"] == "Italian" else row["rating"],
    axis=1
)

df

   id            name      cuisine  rating  delivery_charge  final_rating
0   1          Swagat     Gujarati     4.3               50           4.3
1   2    Cafe Delight  Continental     3.7               50           3.7
2   3  Mainland China      Chinese     4.7               50           4.7

In [5]:
#Task 5: Automate daily summary - restaurants with rating above 4.5 saved to CSV
connection2 = sqlite3.connect("foodie.db")

summary_df = pd.read_sql_query("SELECT * FROM Restaurants WHERE rating > 4.5", connection2)

summary_df.to_csv("top_rated_restaurants.csv", index=False)

print("Saved", len(summary_df), "rows to top_rated_restaurants.csv")
summary_df

Saved 1 rows to top_rated_restaurants.csv

   id            name  cuisine  rating
0   3  Mainland China  Chinese     4.7